### ISSUE TITLE
クイズモード：説明画面でAPI適用

### ISSUE THREAD

**Issue by Togo555-mp4** [NIT-Anan-Procon/procon32-Lets-AIdea-react#112]
## 概要
説明画面でAPIを適用
使うAPI：API/Start.php

## 具体的にやること

- [x] axiosを使ってAPIを使用する

## ゴール・目的（完成物の定義）
APIから情報を取得して表示するようになる

**Comment by nemuki** [comment]
どのAPIを使うとかリンクがあればよかったかも

**Comment by Togo555-mp4** [comment]
書いておきます
