### ISSUE TITLE
クイズモード：自分に投票できなくする

### ISSUE THREAD

**Issue by Togo555-mp4** [NIT-Anan-Procon/procon32-Lets-AIdea-react#125]
## 概要
クイズモードの投票画面で自分に投票しなくする

## 具体的にやること

- [x] 自分のplayerIDの投票を禁止

## FigmaのURL または UIの画像(あれば)
nothing

## ゴール・目的（完成物の定義）
クイズモードの投票画面で自分に投票しなくする

**Comment by nemuki** [comment]
しなくするって表現やめない？()

**Comment by Togo555-mp4** [comment]
変更しました
