### ISSUE TITLE
共通画面：部屋参加画面

### ISSUE THREAD

**Issue by Togo555-mp4** [NIT-Anan-Procon/procon32-Lets-AIdea-react#15]
## 概要
部屋参加画面を作成

## 具体的にやること

- [ ] 部屋ID入力欄
- [ ] ゲーム参加ボタン

## FigmaのURL または UIの画像(あれば)
https://www.figma.com/file/WIztwc1fSUbBcySALtCQYJ/Let-s-AIdea-UI?node-id=3%3A239

## ゴール・目的（完成物の定義）
部屋参加画面の完成

**Comment by Maoki55** [comment]
UIの仕様変更により、実装しなくなったので閉じます
