### ISSUE TITLE
ライブラリ画面：学習モード

### ISSUE THREAD

**Issue by Togo555-mp4** [NIT-Anan-Procon/procon32-Lets-AIdea-react#16]
## 概要
学習モード作品のライブラリ画面を作成

## 具体的にやること

- [ ] 優秀賞の画像、説明文、作者のアイコンを表示する
- [ ] モード切替ボタン（クイズモードの作品のライブラリ画像に遷移）
- [ ] 戻るボタン（モード選択画面_1に遷移）

## FigmaのURL または UIの画像(あれば)
https://www.figma.com/file/khiRM2ry7rhXdLDLA2gD74/Let-s-AIdea-UI?node-id=10%3A7

## ゴール・目的（完成物の定義）
学習モード作品のライブラリ画面の完成

**Comment by ORIKAMIxNEP** [comment]
クイズモードと合体したため閉じます
