### ISSUE TITLE
学習モード：投票画面UI修正

### ISSUE THREAD

**Issue by Togo555-mp4** [NIT-Anan-Procon/procon32-Lets-AIdea-react#166]
## 概要
学習モードの投票画面UI修正

## 具体的にやること

- [ ] ラジオボタンの位置の修正
- [ ] 画面を小さくしても崩れなくする
- [ ] ボタンのフォントを直す
- [ ] 自分に投票できなくする

## FigmaのURL または UIの画像(あれば)
無し

## ゴール・目的（完成物の定義）
学習モードの投票画面UI修正

**Comment by nemuki** [comment]
ボタンメイリオになってるのも
