### ISSUE TITLE
学習モード：投票画面

### ISSUE THREAD

**Issue by nemuki** [NIT-Anan-Procon/procon32-Lets-AIdea-react#167]
## 概要
![image](https://user-images.githubusercontent.com/43571743/133385818-12f60776-c28a-4bee-a566-5e8d8ed5139e.png)
- こんなかんじになっててスクロールが効いてない
- あとボタンがメイリオなきがする

## 具体的にやること

- [ ] スクロールを効かせるように
- [ ] ボタンをNotoに

## FigmaのURL または UIの画像(あれば)
https://www.figma.com/file/WIztwc1fSUbBcySALtCQYJ/Let-s-AIdea-UI?node-id=939%3A2

## ゴール・目的（完成物の定義）
- スクロールができるように
- ボタンをNoto Sans JPに
- 要素の重なりをなくすように

**Comment by Togo555-mp4** [comment]
下のissueでしようとしてました
現在ブランチを立てて作業中です

**Comment by nemuki** [comment]
下とは:thinking:

**Comment by Togo555-mp4** [comment]
#166 です
