### ISSUE TITLE
リロード禁止を学習モードとクイズモードだけに変更

### ISSUE THREAD

**Issue by ORIKAMIxNEP** [NIT-Anan-Procon/procon32-Lets-AIdea-react#179]
## 概要
リロード禁止を学習モードとクイズモードだけに変更

## 具体的にやること

- [x] リロード禁止処理をAppからQuizとLearnだけに移動

## ゴール・目的（完成物の定義）
リロードを学習モードとクイズモード以外ではできるようになる

**Comment by nemuki** [comment]
これ完全に禁止するのではなくてリロードと自分で戻ろうとすると警告が出るような仕様にできないです？
デバッグ時にCtrl + Rが効かないのでちょっと使いにくいです:pray:
めんどくさければやらないでもOKです

**Comment by ORIKAMIxNEP** [comment]
やりますゞ

**Comment by nemuki** [comment]
Ctrl + Rはきいてた:thinking:

**Comment by ORIKAMIxNEP** [comment]
警告出るように仕様変更いたしました！
