### ISSUE TITLE
学習モード(NGワード有り)：説明画面

### ISSUE THREAD

**Issue by Togo555-mp4** [NIT-Anan-Procon/procon32-Lets-AIdea-react#20]
## 概要
学習モードの説明画面を作成

## 具体的にやること

- [ ] 画像の表示
- [ ] 説明の入力欄
- [ ] 制限時間
- [ ] 単語の表示
- [ ] NGワードの表示
- [ ] NGワードの判定

## Figma URL
https://www.figma.com/file/WIztwc1fSUbBcySALtCQYJ/Let-s-AIdea%E8%AA%AC%E6%98%8E?node-id=260%3A209
https://www.figma.com/file/WIztwc1fSUbBcySALtCQYJ/Let-s-AIdea%E8%AA%AC%E6%98%8E?node-id=260%3A234
https://www.figma.com/file/WIztwc1fSUbBcySALtCQYJ/Let-s-AIdea%E8%AA%AC%E6%98%8E?node-id=260%3A259

## ゴール・目的（完成物の定義）
学習モードの説明画面の完成

**Comment by Togo555-mp4** [comment]
モード変更は実装できない可能性が高いため

**Comment by nemuki** [comment]
> モード変更は実装できない可能性が高いため

閉じるのか開けるのかよくわからないので最後まで書いてもらって

**Comment by Togo555-mp4** [comment]
モード変更は実装できない可能性が高いためこのissueを閉じます
