### ISSUE TITLE
待機画面から説明画面へ遷移しないバグ

### ISSUE THREAD

**Issue by Maoki55** [NIT-Anan-Procon/procon32-Lets-AIdea-react#200]
## 概要
オーナーがゲーム開始ボタンを押しても、その他の参加者が説明画面へ移動しないバグを解消する

## 再現手順 （再現できていない場合や目に見えないものはその旨書く）
- プレイヤーを3人集める
- クイズモードの部屋を立てて3人で入る
- オーナーがスタートボタンを押す

## 不具合・バグの想定される原因（特定できてない場合は、その旨書く）
特定できていない

## 不具合・バグが実際にユーザーに与え得ている与える影響
- オーナー以外はゲームが始まらない

## 解決方法の提案（あれば）
- 画面遷移の関数が動いていない可能性が高いため、関数の実行順序を変更してみる

**Comment by nemuki** [comment]
https://anct-procon.slack.com/archives/C026QV3BUFR/p1632360315075500?thread_ts=1632358527.068500&cid=C026QV3BUFR

これアイコンのプロパティがエラーが起きてるのでは？

**Comment by Maoki55** [comment]
待機画面は正常に表示でき、さらにそのエラーが起きたのはリザルト画面だったので関係ないと考えましたがどうなんでしょうか。consoleにも待機画面ではエラーがでなかったです。

**Comment by Maoki55** [comment]
Waiting.jsxの2つ目のuseEffect()にある第二引数の[]を削除したら画面は遷移するようになりました。
しかし、そうするとclearInterval(timer.current);が実行されず画面遷移してもGetRoomInfo.phpを実行し続けるのが問題なので、それを修正する必要があります。

**Comment by Maoki55** [comment]
なおりました！プルリク出します
