### ISSUE TITLE
APIの切り替えが面倒なのでdotenvを入れて環境変数として管理する

### ISSUE THREAD

**Issue by nemuki** [NIT-Anan-Procon/procon32-Lets-AIdea-react#215]
## 概要
mainのAPIとdevelopのAPIでURLに違いがあり、全てをいちいち変えるのはとてもめんどくさいのでdotenvを導入して環境変数として管理する

## 具体的にやること

- [x] npmでdotenvの導入
- [x] .envファイルの追加
- [x] `http://localhost/`になっている部分を`process.env.API`に変更する

## FigmaのURL または UIの画像(あれば)
なし

## ゴール・目的（完成物の定義）
.envファイルの中身を変更したらAPIも変更される

**Comment by ORIKAMIxNEP** [comment]
プルリク通っているissueなので閉じます
