### ISSUE TITLE
投票画面：画面遷移スキップボタンを作成

### ISSUE THREAD

**Issue by Togo555-mp4** [NIT-Anan-Procon/procon32-Lets-AIdea-react#222]
## 概要
投票画面で制限時間がくる前に画面遷移するボタンを用意し、全員が押したら画面遷移させる

## 具体的にやること

- [x] submitボタンを設置
- [x] submitボタンを押すとデータを送信
- [x] 一度submitボタンを押すとラジオボタンとsubmitボタンを無効化
- [x] GetVoterのAPIを毎秒呼び出し、戻り値が０のとき画面遷移

## FigmaのURL または UIの画像(あれば)
https://www.figma.com/file/WIztwc1fSUbBcySALtCQYJ/Let-s-AIdea-UI?node-id=939%3A2
https://www.figma.com/file/WIztwc1fSUbBcySALtCQYJ/Let-s-AIdea-UI?node-id=263%3A540

## ゴール・目的（完成物の定義）
投票画面で制限時間がくる前に画面遷移するボタンを作る

**Comment by ORIKAMIxNEP** [comment]
投票画面のスキップボタンは現在中田君がこのissueで製作中ですと、「課題部門チャンネル」の吉田先生のメッセージに返信していただけると、、、！
僕ら2人slack落ちてまして
iPhoneの通知からメッセージだけ見ることはできるんです

**Comment by ORIKAMIxNEP** [comment]
マージされたので閉じます
