### ISSUE TITLE
学習モード：投票画面

### ISSUE THREAD

**Issue by Togo555-mp4** [NIT-Anan-Procon/procon32-Lets-AIdea-react#4]
## 概要
学習モードの投票画面を作成

## 具体的にやること

- [x] 画像の表示
- [x] 投票機能の作成
- [x] 人数分のユーザー名、説明文を表示
- [x] ラジオボタン

## Figma URL
https://www.figma.com/file/WIztwc1fSUbBcySALtCQYJ/Let-s-AIdea%E8%AA%AC%E6%98%8E?node-id=260%3A59
https://www.figma.com/file/WIztwc1fSUbBcySALtCQYJ/Let-s-AIdea%E8%AA%AC%E6%98%8E?node-id=260%3A97

## ゴール・目的（完成物の定義）
学習モードの投票画面の完成

**Comment by nemuki** [comment]
![image](https://user-images.githubusercontent.com/43571743/133345139-585d25cb-4db0-4a10-9768-0d86da153b64.png)
割と崩れちゃってた
要素同士の重なりをなくすのと今のままだとオーバーフローが効かずにそのままテキストボックスが大きくなっちゃってる
