### ISSUE TITLE
共通画面：部屋作成画面

### ISSUE THREAD

**Issue by Togo555-mp4** [NIT-Anan-Procon/procon32-Lets-AIdea-react#44]
## 概要
部屋作成画面を作成

## 具体的にやること

- [ ] ボタン
- [ ] 押されたかどうかの判断

## FigmaのURL または UIの画像(あれば)
https://www.figma.com/file/WIztwc1fSUbBcySALtCQYJ/Let-s-AIdea-UI?node-id=344%3A30

## ゴール・目的（完成物の定義）
部屋作成画面の完成

**Comment by Maoki55** [comment]
モード選択画面は一旦完成したのでこれは閉じます
