### ISSUE TITLE
選択画面のコンポーネント作成

### ISSUE THREAD

**Issue by Maoki55** [NIT-Anan-Procon/procon32-Lets-AIdea-react#78]
## 概要
選択画面のコンポーネントを作成

## 具体的にやること

- [x] 2個のボタンの配置
- [x] ボタンのデザイン

## FigmaのURL または UIの画像(あれば)
https://www.figma.com/file/WIztwc1fSUbBcySALtCQYJ/Let-s-AIdea-UI?node-id=3%3A312

## ゴール・目的（完成物の定義）
選択画面のコンポーネントの作成

**Comment by ORIKAMIxNEP** [comment]
画面がなくなってしまったので閉じます
